---
title: eDNA detections quality control
output: html_document
editor_options: 
  chunk_output_type: console
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "docs") })
---

<style type="text/css">
.main-container {
  max-width: 1200px !important;
  margin: auto;
}
</style>

The table below shows the likelihood score of eDNA detections based on WoRMS distributions, species thermal envelopes, and distance to known observations in OBIS and GBIF.

```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(dplyr)
library(purrr)
library(speedy)
library(stringr)
library(ggplot2)
library(sf)
library(glue)
library(formattable)
library(tidyr)

fish_classes <- c("Actinopteri", "Cladistii", "Coelacanthi", "Elasmobranchii", "Holocephali", "Myxini", "Petromyzonti", "Teleostei")
turtle_orders <- c("Testudines")
mammal_classes <- c("Mammalia")
st_qc <- storr::storr_rds("storr_qc")
max_distance <- 5000
coord_round <- 3
options(knitr.kable.NA = "")
```

```{r, message=FALSE, warning=FALSE, cache=TRUE, echo=FALSE}
# read eDNA results

dna_files <- list.files("edna-results/data", "*DNADerivedData*", full.names = TRUE)
occurrence_files <- list.files("edna-results/data", "*Occurrence*", full.names = TRUE)

dna <- map(dna_files, read.table, sep = "\t", quote = "", header = TRUE) %>%
  bind_rows() %>%
  mutate_if(is.character, na_if, "")

occurrence <- map(occurrence_files, read.table, sep = "\t", quote = "", header = TRUE) %>%
  bind_rows() %>%
  mutate_if(is.character, na_if, "") %>%
  mutate(
    aphiaid = str_replace(scientificNameID, "urn:lsid:marinespecies.org:taxname:", ""),
    species = ifelse(taxonRank == "species", scientificName, NA)
  ) %>%
  left_join(dna, by = "occurrenceID")

# add groups

occurrence <- occurrence %>%
  mutate(
    group = case_when(
      class %in% fish_classes ~ "fish",
      order %in% turtle_orders ~ "turtle",
      class %in% mammal_classes ~ "mammal"
    )
  )

# add qc

detections <- occurrence %>%
  filter(!is.na(species) & !is.na(decimalLongitude)) %>%
  group_by(higherGeography, decimalLongitude, decimalLatitude, species, class, family, group, aphiaid) %>%
  summarize() %>%
  ungroup() %>%
  mutate(key = glue("{aphiaid}_{round(decimalLongitude, 3)}_{round(decimalLatitude, 3)}"))

qc_list <- st_qc$mget(detections$key)
names(qc_list) <- detections$key
qc <- bind_rows(qc_list, .id = "key")

detections <- detections %>%
  left_join(qc, by = "key")

detections <- detections %>%
  group_by(higherGeography, species) %>%
  filter(row_number() == 1) %>%
  rowwise() %>%
  mutate(distance = round(distance / 1000)) %>% 
  mutate(across(where(is.character), ~replace_na(.,""))) %>%
  mutate(
    score = ifelse(
      worms, 1, ifelse(
        thermal,
        max(1 * (max_distance - distance) / max_distance, 0),
        max(0.5 * (max_distance - distance) / max_distance, 0)
      )
    )
  ) %>%
  mutate(score = round(score, 2)) %>%
  select(site = higherGeography, class, family, species, group, distance, worms, thermal, score, aphiaid) %>%
  arrange(site, species)

rm("occurrence", "dna", "qc_list", "qc")
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
icon_formatter <- function() {
  formatter("span", 
    style = x ~ style(color = ifelse(x, "#a7c400", "#f57842")), x ~ icontext(ifelse(x, "ok", "remove"), "")
  )	 	 
}

distant_formatter <- function() {
  formatter("span", 
    style = ~ style(color = ifelse(distance > max_distance, "#f57842", "black"))
  )	 	 
} 

ft <- detections %>%
  mutate(species = glue("<a target=\"_blank\" href=\"https://www.marinespecies.org/aphia.php?p=taxdetails&id={aphiaid}\">{species}</a>")) %>%
  select(-aphiaid) %>%
  formattable(
    align = rep("l", 6),
    list(
      score = color_tile("#f57842", "#ffffff"),
      distance = distant_formatter(),
      worms = icon_formatter(),
      thermal = icon_formatter()
    )
  )
ft %>%
  as.datatable(escape = FALSE, rownames = FALSE, filter = "none", options = list(pageLength = 500))
```
